server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/proj_demo?useSSL=true&useUnicode=true&characterEncoding=UTF-8
mybatis-plus:
  configuration:
    #we configure the output of the underlying SQL to facilitate observing the SQL statements
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
